/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core'
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, NetworkOnly, StaleWhileRevalidate } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { RangeRequestsPlugin } from 'workbox-range-requests'

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision: string }>
}

clientsClaim()
cleanupOutdatedCaches()

// Ensure the newest service worker activates immediately after installation.
// This prevents Safari/iPad from continuing to serve a previous cached UI.
self.addEventListener('install', (event) => {
  event.waitUntil(self.skipWaiting())
})

// Precache build assets (generated by VitePWA)
precacheAndRoute(self.__WB_MANIFEST)

// SPA navigation fallback
registerRoute(
  ({ request, url }) => request.mode === 'navigate' && !url.pathname.startsWith('/api/'),
  createHandlerBoundToURL('/index.html'),
)

// MP4 caching with range request support (better seeking offline)
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.mp4'),
  new CacheFirst({
    cacheName: 'video-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [200] }),
      new RangeRequestsPlugin(),
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 30 }),
    ],
  }),
)

// WebM caching with range requests for generated school/homework media.
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.webm'),
  new CacheFirst({
    cacheName: 'video-webm-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [200] }),
      new RangeRequestsPlugin(),
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 30 }),
    ],
  }),
)

// Runtime image caching for covers, storyboard images, and posters.
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin &&
    (url.pathname.endsWith('.png') ||
      url.pathname.endsWith('.jpg') ||
      url.pathname.endsWith('.jpeg') ||
      url.pathname.endsWith('.webp')),
  new StaleWhileRevalidate({
    cacheName: 'image-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 300, maxAgeSeconds: 60 * 60 * 24 * 60 }),
    ],
  }),
)

// Curriculum JSON (if served as separate assets)
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.json') && url.pathname.includes('curriculum-'),
  new StaleWhileRevalidate({
    cacheName: 'curriculum-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 7 })],
  }),
)

// Offline-saved ebooks (saved by the app into Cache Storage)
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.startsWith('/offline-ebooks/') && url.pathname.endsWith('.pdf'),
  new CacheFirst({
    cacheName: 'ebook-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [200] }),
      new ExpirationPlugin({ maxEntries: 25, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  }),
)

// Never cache sensitive entitlement / payment / homework endpoints (register before generic /api/*).
const SENSITIVE_API_PREFIXES = [
  '/api/download-ebook',
  '/api/create-checkout-session',
  '/api/create-ebook-checkout-session',
  '/api/process-homework',
  '/api/homework/',
  '/api/generate-visuals',
  '/api/generate-adventure-video',
  '/api/tts',
  '/api/schools/',
]
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin &&
    SENSITIVE_API_PREFIXES.some((prefix) => url.pathname.startsWith(prefix)),
  new NetworkOnly(),
)

// Other API calls: prefer network but allow short offline fallback for cached responses
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 6,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 5 }),
    ],
  }),
)

